[project]
name = "filesearch"
version = "0.2.0"
description = "CLI tool to search filenames by keyword"
authors = [{ name = "Richard Li" }]
requires-python = ">=3.7"
readme = "README.md"
license = { text = "MIT" }

[project.scripts]
fs = "filesearch:main"